// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdclmxxdfkbuiuyknavf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkY2xteHhkZmtidWl1eWtuYXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDI3OTUsImV4cCI6MjA2NTQ3ODc5NX0.qrZMQ4OAVSgqWkhEHjBmXAsWQUbaPczKWIOMmg6J_nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);